---
kind: pipeline
name: e2e-kubernetes-1.16

platform:
  os: linux
  arch: amd64

steps:
  - name: init
    image: quay.io/sighup/e2e-testing-drone-plugin:v0.1.0-rc11
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ clone ]
    settings:
      action: cluster-116
      pipeline_id: cluster-116
      instance_path: /shared
      aws_default_region:
        from_secret: aws_region
      aws_access_key_id:
        from_secret: aws_access_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
      terraform_tf_states_bucket_name:
        from_secret: terraform_tf_states_bucket_name
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/pull/**
          - refs/tags/**

  - name: e2e-basic-istio
    image: quay.io/sighup/e2e-testing:1.1.0_0.1.3_2.16.1_1.4.0_1.16.3_3.2.2_2.4.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ init ]
    commands:
      - export CLUSTER_NAME=116
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export KUBECONFIG=/shared/kube/kubeconfig-116
      - bats -t katalog/tests/istio/istio-minimal-install.sh
      - bats -t katalog/tests/istio/istio-minimal.sh
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/pull/**
          - refs/tags/**

  - name: e2e-egress-gateway
    image: quay.io/sighup/e2e-testing:1.1.0_0.1.3_2.16.1_1.4.0_1.16.3_3.2.2_2.4.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ e2e-basic-istio ]
    commands:
      - export CLUSTER_NAME=116
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export KUBECONFIG=/shared/kube/kubeconfig-116
      - bats -t katalog/tests/istio/istio-egress-install.sh
      - bats -t katalog/tests/istio/istio-egress-external-services.sh
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/pull/**
          - refs/tags/**

  - name: e2e-istio-with-citadel
    image: quay.io/sighup/e2e-testing:1.1.0_0.1.3_2.16.1_1.4.0_1.16.3_3.2.2_2.4.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ e2e-egress-gateway ]
    commands:
      - export CLUSTER_NAME=116
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export KUBECONFIG=/shared/kube/kubeconfig-116
      - bats -t katalog/tests/istio/istio-citadel-install.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-install.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-1.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-2.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-3.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-cleanup.sh
      - bats -t katalog/tests/istio/istio-citadel-rollback.sh
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/pull/**
          - refs/tags/**

  - name: e2e-istio-with-citadel-and-sidecar-injector
    image: quay.io/sighup/e2e-testing:1.1.0_0.1.3_2.16.1_1.4.0_1.16.3_3.2.2_2.4.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ e2e-istio-with-citadel ]
    commands:
      - export CLUSTER_NAME=116
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export KUBECONFIG=/shared/kube/kubeconfig-116
      - bats -t katalog/tests/istio/istio-citadel-sidecar-injector-install.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-sidecar-injector-install.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-1.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-2.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-3.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-cleanup.sh
      - bats -t katalog/tests/istio/istio-citadel-rollback.sh
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/pull/**
          - refs/tags/**

  - name: e2e-basic-istio-and-sidecar-injector
    image: quay.io/sighup/e2e-testing:1.1.0_0.1.3_2.16.1_1.4.0_1.16.3_3.2.2_2.4.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ e2e-istio-with-citadel-and-sidecar-injector ]
    commands:
      - export CLUSTER_NAME=116
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export KUBECONFIG=/shared/kube/kubeconfig-116
      - bats -t katalog/tests/istio/istio-minimal-sidecar-injector.sh
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/pull/**
          - refs/tags/**

  - name: destroy
    image: quay.io/sighup/e2e-testing-drone-plugin:v0.1.0-rc11
    pull: always
    depends_on: [ e2e-basic-istio-and-sidecar-injector ]
    settings:
      action: destroy
      pipeline_id: cluster-116
      aws_default_region:
        from_secret: aws_region
      aws_access_key_id:
        from_secret: aws_access_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
      terraform_tf_states_bucket_name:
        from_secret: terraform_tf_states_bucket_name
    when:
      status:
      - success
      - failure

volumes:
- name: shared
  temp: {}

---
kind: pipeline
name: e2e-kubernetes-1.15

platform:
  os: linux
  arch: amd64

steps:
  - name: init
    image: quay.io/sighup/e2e-testing-drone-plugin:v0.1.0-rc11
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ clone ]
    settings:
      action: cluster-115
      pipeline_id: cluster-115
      instance_path: /shared
      aws_default_region:
        from_secret: aws_region
      aws_access_key_id:
        from_secret: aws_access_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
      terraform_tf_states_bucket_name:
        from_secret: terraform_tf_states_bucket_name
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: e2e-basic-istio
    image: quay.io/sighup/e2e-testing:1.1.0_0.1.3_2.16.1_1.4.0_1.15.6_3.2.2_2.4.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ init ]
    commands:
      - export CLUSTER_NAME=115
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export KUBECONFIG=/shared/kube/kubeconfig-115
      - bats -t katalog/tests/istio/istio-minimal-install.sh
      - bats -t katalog/tests/istio/istio-minimal.sh
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: e2e-egress-gateway
    image: quay.io/sighup/e2e-testing:1.1.0_0.1.3_2.16.1_1.4.0_1.15.6_3.2.2_2.4.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ e2e-basic-istio ]
    commands:
      - export CLUSTER_NAME=115
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export KUBECONFIG=/shared/kube/kubeconfig-115
      - bats -t katalog/tests/istio/istio-egress-install.sh
      - bats -t katalog/tests/istio/istio-egress-external-services.sh
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: e2e-istio-with-citadel
    image: quay.io/sighup/e2e-testing:1.1.0_0.1.3_2.16.1_1.4.0_1.15.6_3.2.2_2.4.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ e2e-egress-gateway ]
    commands:
      - export CLUSTER_NAME=115
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export KUBECONFIG=/shared/kube/kubeconfig-115
      - bats -t katalog/tests/istio/istio-citadel-install.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-install.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-1.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-2.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-3.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-cleanup.sh
      - bats -t katalog/tests/istio/istio-citadel-rollback.sh
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: e2e-istio-with-citadel-and-sidecar-injector
    image: quay.io/sighup/e2e-testing:1.1.0_0.1.3_2.16.1_1.4.0_1.15.6_3.2.2_2.4.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ e2e-istio-with-citadel ]
    commands:
      - export CLUSTER_NAME=115
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export KUBECONFIG=/shared/kube/kubeconfig-115
      - bats -t katalog/tests/istio/istio-citadel-sidecar-injector-install.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-sidecar-injector-install.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-1.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-2.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-3.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-cleanup.sh
      - bats -t katalog/tests/istio/istio-citadel-rollback.sh
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: e2e-basic-istio-and-sidecar-injector
    image: quay.io/sighup/e2e-testing:1.1.0_0.1.3_2.16.1_1.4.0_1.15.6_3.2.2_2.4.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ e2e-istio-with-citadel-and-sidecar-injector ]
    commands:
      - export CLUSTER_NAME=115
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export KUBECONFIG=/shared/kube/kubeconfig-115
      - bats -t katalog/tests/istio/istio-minimal-sidecar-injector.sh
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: destroy
    image: quay.io/sighup/e2e-testing-drone-plugin:v0.1.0-rc11
    pull: always
    depends_on: [ e2e-basic-istio-and-sidecar-injector ]
    settings:
      action: destroy
      pipeline_id: cluster-115
      aws_default_region:
        from_secret: aws_region
      aws_access_key_id:
        from_secret: aws_access_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
      terraform_tf_states_bucket_name:
        from_secret: terraform_tf_states_bucket_name
    when:
      status:
      - success
      - failure

volumes:
- name: shared
  temp: {}

---
kind: pipeline
name: e2e-kubernetes-1.14

platform:
  os: linux
  arch: amd64

steps:
  - name: init
    image: quay.io/sighup/e2e-testing-drone-plugin:v0.1.0-rc11
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ clone ]
    settings:
      action: cluster-114
      pipeline_id: cluster-114
      instance_path: /shared
      aws_default_region:
        from_secret: aws_region
      aws_access_key_id:
        from_secret: aws_access_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
      terraform_tf_states_bucket_name:
        from_secret: terraform_tf_states_bucket_name
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: e2e-basic-istio
    image: quay.io/sighup/e2e-testing:1.1.0_0.1.3_2.16.1_1.4.0_1.14.9_3.2.2_2.4.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ init ]
    commands:
      - export CLUSTER_NAME=114
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export KUBECONFIG=/shared/kube/kubeconfig-114
      - bats -t katalog/tests/istio/istio-minimal-install.sh
      - bats -t katalog/tests/istio/istio-minimal.sh
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: e2e-egress-gateway
    image: quay.io/sighup/e2e-testing:1.1.0_0.1.3_2.16.1_1.4.0_1.14.9_3.2.2_2.4.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ e2e-basic-istio ]
    commands:
      - export CLUSTER_NAME=114
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export KUBECONFIG=/shared/kube/kubeconfig-114
      - bats -t katalog/tests/istio/istio-egress-install.sh
      - bats -t katalog/tests/istio/istio-egress-external-services.sh
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: e2e-istio-with-citadel
    image: quay.io/sighup/e2e-testing:1.1.0_0.1.3_2.16.1_1.4.0_1.14.9_3.2.2_2.4.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ e2e-egress-gateway ]
    commands:
      - export CLUSTER_NAME=114
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export KUBECONFIG=/shared/kube/kubeconfig-114
      - bats -t katalog/tests/istio/istio-citadel-install.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-install.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-1.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-2.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-3.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-cleanup.sh
      - bats -t katalog/tests/istio/istio-citadel-rollback.sh
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: e2e-istio-with-citadel-and-sidecar-injector
    image: quay.io/sighup/e2e-testing:1.1.0_0.1.3_2.16.1_1.4.0_1.14.9_3.2.2_2.4.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ e2e-istio-with-citadel ]
    commands:
      - export CLUSTER_NAME=114
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export KUBECONFIG=/shared/kube/kubeconfig-114
      - bats -t katalog/tests/istio/istio-citadel-sidecar-injector-install.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-sidecar-injector-install.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-1.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-2.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-3.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-cleanup.sh
      - bats -t katalog/tests/istio/istio-citadel-rollback.sh
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: e2e-basic-istio-and-sidecar-injector
    image: quay.io/sighup/e2e-testing:1.1.0_0.1.3_2.16.1_1.4.0_1.14.9_3.2.2_2.4.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ e2e-istio-with-citadel-and-sidecar-injector ]
    commands:
      - export CLUSTER_NAME=114
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export KUBECONFIG=/shared/kube/kubeconfig-114
      - bats -t katalog/tests/istio/istio-minimal-sidecar-injector.sh
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: destroy
    image: quay.io/sighup/e2e-testing-drone-plugin:v0.1.0-rc11
    pull: always
    depends_on: [ e2e-basic-istio-and-sidecar-injector ]
    settings:
      action: destroy
      pipeline_id: cluster-114
      aws_default_region:
        from_secret: aws_region
      aws_access_key_id:
        from_secret: aws_access_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
      terraform_tf_states_bucket_name:
        from_secret: terraform_tf_states_bucket_name
    when:
      status:
      - success
      - failure

volumes:
- name: shared
  temp: {}