# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

name: e2e-kubernetes-1.18
kind: pipeline
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: init
    image: quay.io/sighup/e2e-testing-drone-plugin:v0.10.0
    pull: always
    volumes:
      - name: shared
        path: /shared
    depends_on: [clone]
    settings:
      action: custom-cluster-118
      local_kind_config_path: katalog/tests/istio-operator/kind-config.yml
      instance_size: 2-extra-large
      cluster_version: "1.18.8"
      pipeline_id: cluster-118
      instance_path: /shared
      aws_default_region:
        from_secret: aws_region
      aws_access_key_id:
        from_secret: aws_access_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
      terraform_tf_states_bucket_name:
        from_secret: terraform_tf_states_bucket_name
      vsphere_server:
        from_secret: vsphere_server
      vsphere_password:
        from_secret: vsphere_password
      vsphere_user:
        from_secret: vsphere_user
      dockerhub_username:
        from_secret: dockerhub_username
      dockerhub_password:
        from_secret: dockerhub_password
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: e2e-requirements
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.9.4_1.18.8_3.8.7_2.4.1
    pull: always
    volumes:
      - name: shared
        path: /shared
    depends_on: [init]
    commands:
      - export CLUSTER_NAME=118
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export KUBECONFIG=/shared/kube/kubeconfig-118
      - cd katalog/tests/istio-operator/requirements
      - furyctl vendor -H
      - cd ../../../../
      - bats -t katalog/tests/istio-operator/istio-requirements.sh
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: e2e-basic-istio
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.9.4_1.18.8_3.8.7_2.4.1
    pull: always
    volumes:
      - name: shared
        path: /shared
    depends_on: [e2e-requirements]
    commands:
      - export CLUSTER_NAME=118
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export KUBECONFIG=/shared/kube/kubeconfig-118
      - cat /shared/machine/private_key
      - cat $KUBECONFIG
      - bats -t katalog/tests/istio-operator/istio-minimal-install.sh
      - bats -t katalog/tests/istio-operator/istio-minimal.sh
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: e2e-egress-gateway
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.9.4_1.18.8_3.8.7_2.4.1
    pull: always
    volumes:
      - name: shared
        path: /shared
    depends_on: [e2e-basic-istio]
    commands:
      - export CLUSTER_NAME=118
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export KUBECONFIG=/shared/kube/kubeconfig-118
      - bats -t katalog/tests/istio-operator/istio-egress-install.sh
      - bats -t katalog/tests/istio-operator/istio-egress-external-services.sh
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: e2e-istio-with-citadel
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.9.4_1.18.8_3.8.7_2.4.1
    pull: always
    volumes:
      - name: shared
        path: /shared
    depends_on: [e2e-egress-gateway]
    commands:
      - export CLUSTER_NAME=118
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export KUBECONFIG=/shared/kube/kubeconfig-118
      - bats -t katalog/tests/istio-operator/istio-citadel-authn-install.sh
      - bats -t katalog/tests/istio-operator/istio-citadel-authn-1.sh
      - bats -t katalog/tests/istio-operator/istio-citadel-authn-2.sh
      - bats -t katalog/tests/istio-operator/istio-citadel-authn-3.sh
      - bats -t katalog/tests/istio-operator/istio-citadel-authn-cleanup.sh
      - bats -t katalog/tests/istio-operator/istio-citadel-rollback.sh
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: wait_for_debug
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.9.4_1.18.8_3.8.7_2.4.1
    pull: always
    depends_on: [e2e-istio-with-citadel]
    commands:
      - sleep 1h
    when:
      status:
        - failure

  - name: destroy
    image: quay.io/sighup/e2e-testing-drone-plugin:v0.10.0
    pull: always
    depends_on: [wait_for_debug]
    settings:
      action: destroy
      pipeline_id: cluster-118
      aws_default_region:
        from_secret: aws_region
      aws_access_key_id:
        from_secret: aws_access_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
      terraform_tf_states_bucket_name:
        from_secret: terraform_tf_states_bucket_name
      vsphere_server:
        from_secret: vsphere_server
      vsphere_password:
        from_secret: vsphere_password
      vsphere_user:
        from_secret: vsphere_user
      dockerhub_username:
        from_secret: dockerhub_username
      dockerhub_password:
        from_secret: dockerhub_password
    when:
      status:
        - success
        - failure

volumes:
  - name: shared
    temp: {}

---
name: e2e-kubernetes-1.19
kind: pipeline
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: init
    image: quay.io/sighup/e2e-testing-drone-plugin:v0.10.0
    pull: always
    volumes:
      - name: shared
        path: /shared
    depends_on: [clone]
    settings:
      action: custom-cluster-119
      local_kind_config_path: katalog/tests/istio-operator/kind-config.yml
      instance_size: 2-extra-large
      cluster_version: "1.19.4"
      pipeline_id: cluster-119
      instance_path: /shared
      aws_default_region:
        from_secret: aws_region
      aws_access_key_id:
        from_secret: aws_access_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
      terraform_tf_states_bucket_name:
        from_secret: terraform_tf_states_bucket_name
      vsphere_server:
        from_secret: vsphere_server
      vsphere_password:
        from_secret: vsphere_password
      vsphere_user:
        from_secret: vsphere_user
      dockerhub_username:
        from_secret: dockerhub_username
      dockerhub_password:
        from_secret: dockerhub_password
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: e2e-requirements
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.9.4_1.19.4_3.8.7_2.4.1
    pull: always
    volumes:
      - name: shared
        path: /shared
    depends_on: [init]
    commands:
      - export CLUSTER_NAME=119
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export KUBECONFIG=/shared/kube/kubeconfig-119
      - cd katalog/tests/istio-operator/requirements
      - furyctl vendor -H
      - cd ../../../../
      - bats -t katalog/tests/istio-operator/istio-requirements.sh
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: e2e-basic-istio
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.9.4_1.19.4_3.8.7_2.4.1
    pull: always
    volumes:
      - name: shared
        path: /shared
    depends_on: [e2e-requirements]
    commands:
      - export CLUSTER_NAME=119
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export KUBECONFIG=/shared/kube/kubeconfig-119
      - cat /shared/machine/private_key
      - cat $KUBECONFIG
      - bats -t katalog/tests/istio-operator/istio-minimal-install.sh
      - bats -t katalog/tests/istio-operator/istio-minimal.sh
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: e2e-egress-gateway
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.9.4_1.19.4_3.8.7_2.4.1
    pull: always
    volumes:
      - name: shared
        path: /shared
    depends_on: [e2e-basic-istio]
    commands:
      - export CLUSTER_NAME=119
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export KUBECONFIG=/shared/kube/kubeconfig-119
      - bats -t katalog/tests/istio-operator/istio-egress-install.sh
      - bats -t katalog/tests/istio-operator/istio-egress-external-services.sh
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: e2e-istio-with-citadel
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.9.4_1.19.4_3.8.7_2.4.1
    pull: always
    volumes:
      - name: shared
        path: /shared
    depends_on: [e2e-egress-gateway]
    commands:
      - export CLUSTER_NAME=119
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export KUBECONFIG=/shared/kube/kubeconfig-119
      - bats -t katalog/tests/istio-operator/istio-citadel-authn-install.sh
      - bats -t katalog/tests/istio-operator/istio-citadel-authn-1.sh
      - bats -t katalog/tests/istio-operator/istio-citadel-authn-2.sh
      - bats -t katalog/tests/istio-operator/istio-citadel-authn-3.sh
      - bats -t katalog/tests/istio-operator/istio-citadel-authn-cleanup.sh
      - bats -t katalog/tests/istio-operator/istio-citadel-rollback.sh
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: wait_for_debug
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.9.4_1.19.4_3.8.7_2.4.1
    pull: always
    depends_on: [e2e-istio-with-citadel]
    commands:
      - sleep 1h
    when:
      status:
        - failure

  - name: destroy
    image: quay.io/sighup/e2e-testing-drone-plugin:v0.10.0
    pull: always
    depends_on: [wait_for_debug]
    settings:
      action: destroy
      pipeline_id: cluster-119
      aws_default_region:
        from_secret: aws_region
      aws_access_key_id:
        from_secret: aws_access_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
      terraform_tf_states_bucket_name:
        from_secret: terraform_tf_states_bucket_name
      vsphere_server:
        from_secret: vsphere_server
      vsphere_password:
        from_secret: vsphere_password
      vsphere_user:
        from_secret: vsphere_user
      dockerhub_username:
        from_secret: dockerhub_username
      dockerhub_password:
        from_secret: dockerhub_password
    when:
      status:
        - success
        - failure

volumes:
  - name: shared
    temp: {}

---
name: e2e-kubernetes-1.20
kind: pipeline
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: init
    image: quay.io/sighup/e2e-testing-drone-plugin:v0.10.0
    pull: always
    volumes:
      - name: shared
        path: /shared
    depends_on: [clone]
    settings:
      action: custom-cluster-120
      local_kind_config_path: katalog/tests/istio-operator/kind-config.yml
      instance_size: 2-extra-large
      cluster_version: "1.20.0"
      pipeline_id: cluster-120
      instance_path: /shared
      aws_default_region:
        from_secret: aws_region
      aws_access_key_id:
        from_secret: aws_access_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
      terraform_tf_states_bucket_name:
        from_secret: terraform_tf_states_bucket_name
      vsphere_server:
        from_secret: vsphere_server
      vsphere_password:
        from_secret: vsphere_password
      vsphere_user:
        from_secret: vsphere_user
      dockerhub_username:
        from_secret: dockerhub_username
      dockerhub_password:
        from_secret: dockerhub_password
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: e2e-requirements
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.9.4_1.20.0_3.8.7_2.4.1
    pull: always
    volumes:
      - name: shared
        path: /shared
    depends_on: [init]
    commands:
      - export CLUSTER_NAME=120
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export KUBECONFIG=/shared/kube/kubeconfig-120
      - cd katalog/tests/istio-operator/requirements
      - furyctl vendor -H
      - cd ../../../../
      - bats -t katalog/tests/istio-operator/istio-requirements.sh
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: e2e-basic-istio
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.9.4_1.20.0_3.8.7_2.4.1
    pull: always
    volumes:
      - name: shared
        path: /shared
    depends_on: [e2e-requirements]
    commands:
      - export CLUSTER_NAME=120
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export KUBECONFIG=/shared/kube/kubeconfig-120
      - cat /shared/machine/private_key
      - cat $KUBECONFIG
      - bats -t katalog/tests/istio-operator/istio-minimal-install.sh
      - bats -t katalog/tests/istio-operator/istio-minimal.sh
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: e2e-egress-gateway
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.9.4_1.20.0_3.8.7_2.4.1
    pull: always
    volumes:
      - name: shared
        path: /shared
    depends_on: [e2e-basic-istio]
    commands:
      - export CLUSTER_NAME=120
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export KUBECONFIG=/shared/kube/kubeconfig-120
      - bats -t katalog/tests/istio-operator/istio-egress-install.sh
      - bats -t katalog/tests/istio-operator/istio-egress-external-services.sh
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: e2e-istio-with-citadel
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.9.4_1.20.0_3.8.7_2.4.1
    pull: always
    volumes:
      - name: shared
        path: /shared
    depends_on: [e2e-egress-gateway]
    commands:
      - export CLUSTER_NAME=120
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export KUBECONFIG=/shared/kube/kubeconfig-120
      - bats -t katalog/tests/istio-operator/istio-citadel-authn-install.sh
      - bats -t katalog/tests/istio-operator/istio-citadel-authn-1.sh
      - bats -t katalog/tests/istio-operator/istio-citadel-authn-2.sh
      - bats -t katalog/tests/istio-operator/istio-citadel-authn-3.sh
      - bats -t katalog/tests/istio-operator/istio-citadel-authn-cleanup.sh
      - bats -t katalog/tests/istio-operator/istio-citadel-rollback.sh
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: wait_for_debug
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.9.4_1.20.0_3.8.7_2.4.1
    pull: always
    depends_on: [e2e-istio-with-citadel]
    commands:
      - sleep 1h
    when:
      status:
        - failure

  - name: destroy
    image: quay.io/sighup/e2e-testing-drone-plugin:v0.10.0
    pull: always
    depends_on: [wait_for_debug]
    settings:
      action: destroy
      pipeline_id: cluster-120
      aws_default_region:
        from_secret: aws_region
      aws_access_key_id:
        from_secret: aws_access_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
      terraform_tf_states_bucket_name:
        from_secret: terraform_tf_states_bucket_name
      vsphere_server:
        from_secret: vsphere_server
      vsphere_password:
        from_secret: vsphere_password
      vsphere_user:
        from_secret: vsphere_user
      dockerhub_username:
        from_secret: dockerhub_username
      dockerhub_password:
        from_secret: dockerhub_password
    when:
      status:
        - success
        - failure

volumes:
  - name: shared
    temp: {}
