{
 "title": "Kuma Dataplane",
 "description": "Statistics of a single Dataplane in Kuma Service Mesh",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "mesh",
    "label": "Mesh",
    "query": "label_values(envoy_server_live, mesh)"
   },
   {
    "name": "dataplane",
    "label": "Dataplane",
    "query": "label_values(envoy_server_live{mesh=\"$mesh\"}, dataplane)"
   }
  ]
 },
 "panels": [
  { "title": "Dataplane", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(envoy_server_live{dataplane=\"$dataplane\",mesh=\"$mesh\"} OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 1 },
   "format": "s",
   "valueName": "max",
   "targets": [
    {
     "expr": "envoy_server_uptime{dataplane=\"$dataplane\",mesh=\"$mesh\"}"
    }
   ]
  },
  {
   "title": "Heap size",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 9, "y": 1 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "envoy_server_memory_heap_size{dataplane=\"$dataplane\",mesh=\"$mesh\"}"
    }
   ]
  },
  {
   "title": "Memory allocated",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 13, "y": 1 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "envoy_server_memory_allocated{dataplane=\"$dataplane\",mesh=\"$mesh\"}"
    }
   ]
  },
  {
   "title": "Connection to the Control Plane",
   "type": "graph",
   "description": "Note that if Control Plane does not sent FIN segment, Dataplanes can still think that connection is up waiting for new update even that Control Plane is down.",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_control_plane_connected_state{dataplane=\"$dataplane\",mesh=\"$mesh\"}",
     "legendFormat": "Connected"
    }
   ]
  },
  { "title": "Incoming traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Active Connections to this Dataplane",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_upstream_cx_active{dataplane=\"$dataplane\",mesh=\"$mesh\",envoy_cluster_name=~\"localhost.*\"}",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Connection time (P99)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, irate(envoy_cluster_upstream_cx_connect_ms_bucket{dataplane=\"$dataplane\",envoy_cluster_name=~\"localhost.*\",mesh=\"$mesh\"}[1m]))",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Connection length (P99)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, irate(envoy_cluster_upstream_cx_length_ms_bucket{dataplane=\"$dataplane\",envoy_cluster_name=~\"localhost.*\",mesh=\"$mesh\"}[1m]))",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Bytes received from requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(envoy_cluster_upstream_cx_tx_bytes_total{dataplane=\"$dataplane\",envoy_cluster_name=~\"localhost.*\",mesh=\"$mesh\"}[1m])",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Bytes sent in responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(envoy_cluster_upstream_cx_rx_bytes_total{dataplane=\"$dataplane\",envoy_cluster_name=~\"localhost.*\",mesh=\"$mesh\"}[1m])",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Traffic permissions",
   "type": "graph",
   "description": "Data is only available if TrafficPermission policy is applied.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(envoy_rbac_allowed{dataplane=\"$dataplane\",mesh=\"$mesh\"}[1m])",
     "legendFormat": "Allowed - {{listener}}"
    },
    {
     "expr": "irate(envoy_rbac_shadow_allowed{dataplane=\"$dataplane\",mesh=\"$mesh\"}[1m])",
     "legendFormat": "Shadow allowed - {{listener}}"
    },
    {
     "expr": "irate(envoy_rbac_denied{dataplane=\"$dataplane\",mesh=\"$mesh\"}[1m])",
     "legendFormat": "Denied - {{listener}}"
    },
    {
     "expr": "irate(envoy_rbac_shadow_denied{dataplane=\"$dataplane\",mesh=\"$mesh\"}[1m])",
     "legendFormat": "Shadow denied - {{listener}}"
    }
   ]
  },
  {
   "title": "Connection/Requests errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(envoy_cluster_upstream_cx_connect_timeout{dataplane=\"$dataplane\",mesh=\"$mesh\",envoy_cluster_name=~\"localhost.*\"}[1m])",
     "legendFormat": "connection timeout - {{envoy_cluster_name}}"
    },
    {
     "expr": "irate(envoy_cluster_upstream_rq_pending_failure_eject{dataplane=\"$dataplane\",mesh=\"$mesh\",envoy_cluster_name=~\"localhost.*\"}[1m])",
     "legendFormat": "pending failure ejection - {{envoy_cluster_name}}"
    },
    {
     "expr": "irate(envoy_cluster_upstream_rq_pending_overflow{dataplane=\"$dataplane\",mesh=\"$mesh\",envoy_cluster_name=~\"localhost.*\"}[1m])",
     "legendFormat": "pending overflow - {{envoy_cluster_name}}"
    },
    {
     "expr": "irate(envoy_cluster_upstream_rq_timeout{dataplane=\"$dataplane\",mesh=\"$mesh\",envoy_cluster_name=~\"localhost.*\"}[1m])",
     "legendFormat": "request timeout - {{envoy_cluster_name}}"
    },
    {
     "expr": "irate(envoy_cluster_upstream_rq_rx_reset{dataplane=\"$dataplane\",mesh=\"$mesh\",envoy_cluster_name=~\"localhost.*\"}[1m])",
     "legendFormat": "response reset by the client - {{envoy_cluster_name}}"
    },
    {
     "expr": "irate(envoy_cluster_upstream_rq_tx_reset{dataplane=\"$dataplane\",mesh=\"$mesh\",envoy_cluster_name=~\"localhost.*\"}[1m])",
     "legendFormat": "request reset by local Envoy - {{envoy_cluster_name}}"
    }
   ]
  },
  { "title": "Outgoing traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Active Connections to other Dataplanes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_upstream_cx_active{dataplane=\"$dataplane\",mesh=\"$mesh\",envoy_cluster_name!~\"(localhost.*)|ads_cluster|kuma_envoy_admin|access_log_sink\"}",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Connection time (P99)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, irate(envoy_cluster_upstream_cx_connect_ms_bucket{dataplane=\"$dataplane\",envoy_cluster_name!~\"(localhost.*)|ads_cluster|kuma_envoy_admin|access_log_sink\",mesh=\"$mesh\"}[1m]))",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Connection length (P99)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, irate(envoy_cluster_upstream_cx_length_ms_bucket{dataplane=\"$dataplane\",envoy_cluster_name!~\"(localhost.*)|ads_cluster|kuma_envoy_admin|access_log_sink\",mesh=\"$mesh\"}[1m]))",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Bytes received from other Dataplanes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(envoy_cluster_upstream_cx_rx_bytes_total{dataplane=\"$dataplane\",envoy_cluster_name!~\"(localhost.*)|ads_cluster|kuma_envoy_admin|access_log_sink\",mesh=\"$mesh\"}[1m])",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Bytes sent to other Dataplanes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(envoy_cluster_upstream_cx_tx_bytes_total{dataplane=\"$dataplane\",envoy_cluster_name!~\"(localhost.*)|ads_cluster|kuma_envoy_admin|access_log_sink\",mesh=\"$mesh\"}[1m])",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Secured destinations by mTLS",
   "type": "table",
   "description": "Data is only available if TrafficPermission policy is applied.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
   "targets": [
    {
     "expr": "envoy_cluster_ssl_handshake{dataplane=\"$dataplane\",mesh=\"$mesh\"} > 0",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Connection/Requests errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(envoy_cluster_upstream_cx_connect_timeout{dataplane=\"$dataplane\",mesh=\"$mesh\",envoy_cluster_name!~\"(localhost.*)|ads_cluster|kuma_envoy_admin|access_log_sink\"}[1m])",
     "legendFormat": "connection timeout - {{envoy_cluster_name}}"
    },
    {
     "expr": "irate(envoy_cluster_upstream_rq_pending_failure_eject{dataplane=\"$dataplane\",mesh=\"$mesh\",envoy_cluster_name!~\"(localhost.*)|ads_cluster|kuma_envoy_admin|access_log_sink\"}[1m])",
     "legendFormat": "pending failure ejection - {{envoy_cluster_name}}"
    },
    {
     "expr": "irate(envoy_cluster_upstream_rq_pending_overflow{dataplane=\"$dataplane\",mesh=\"$mesh\",envoy_cluster_name!~\"(localhost.*)|ads_cluster|kuma_envoy_admin|access_log_sink\"}[1m])",
     "legendFormat": "pending overflow - {{envoy_cluster_name}}"
    },
    {
     "expr": "irate(envoy_cluster_upstream_rq_timeout{dataplane=\"$dataplane\",mesh=\"$mesh\",envoy_cluster_name!~\"(localhost.*)|ads_cluster|kuma_envoy_admin|access_log_sink\"}[1m])",
     "legendFormat": "request timeout - {{envoy_cluster_name}}"
    },
    {
     "expr": "irate(envoy_cluster_upstream_rq_rx_reset{dataplane=\"$dataplane\",mesh=\"$mesh\",envoy_cluster_name!~\"(localhost.*)|ads_cluster|kuma_envoy_admin|access_log_sink\"}[1m])",
     "legendFormat": "request reset by other Envoy - {{envoy_cluster_name}}"
    },
    {
     "expr": "irate(envoy_cluster_upstream_rq_tx_reset{dataplane=\"$dataplane\",mesh=\"$mesh\",envoy_cluster_name!~\"(localhost.*)|ads_cluster|kuma_envoy_admin|access_log_sink\"}[1m])",
     "legendFormat": "response reset by local Envoy - {{envoy_cluster_name}}"
    }
   ]
  },
  { "title": "Health Checks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Active Health Checks - healthy service instances",
   "type": "graph",
   "description": "Data is only available if HealthCheck policy is applied.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_health_check_healthy{dataplane=\"$dataplane\",mesh=\"$mesh\"}",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Active Health Checks - failing service instances",
   "type": "graph",
   "description": "Data is only available if HealthCheck policy is applied.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_membership_total{dataplane=\"$dataplane\",mesh=\"$mesh\"} - envoy_cluster_health_check_healthy{dataplane=\"$dataplane\",mesh=\"$mesh\"}",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Passive Health Checks - failing service instances",
   "type": "graph",
   "description": "Data is only available if HealthCheck policy is applied.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_outlier_detection_ejections_active{dataplane=\"$dataplane\",mesh=\"$mesh\"}",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Passive Health Checks - number of enforced ejections",
   "type": "graph",
   "description": "Data is only available if HealthCheck policy is applied.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(envoy_cluster_outlier_detection_ejections_enforced_total{dataplane=\"$dataplane\",mesh=\"$mesh\"}[1m])",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  }
 ]
}